### ISSUE TITLE
Pierde el foco de al aplicación en uso al pulsar un botón

### ISSUE THREAD

**Issue by Quitoboss** [elModo7/LibreDeck#2]
https://youtu.be/FEaveSZnXEg?t=324
Al pulsar el botón coges el foco de la app y lo pierdes donde querías estar escribiendo.
Se me ocurre que se le puede añadir a la función de presionar el botón que tras la pulsación y antes de ejecutar el comando se envíe un Alt+Tab para que retroceda a la aplicación donde estabas antes de pulsar el botón ¿?

**Comment by elModo7** [comment]
Lo voy a resolver en directo en un rato, subiré versión en que la tenga lista, me di cuenta de eso hace un par de días probando la app, en la mía ya lo tenía porque la uso en la táctil pero es verdad que aunque no uses una pantalla táctil es necesario el cambio de app antes de ejecutar la acción.
Un saludo! 👍
